apiVersion: v1
kind: Config
clusters:
- name: "customer-kne"
  cluster:
    server: "https://rancher.kne.bund.drv/k8s/clusters/c-m-bn7dntbl"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUd6akNDQ\
      mJhZ0F3SUJBZ0lEQ3NqNk1BMEdDU3FHU0liM0RRRUJDd1VBTUdReEN6QUpCZ05WQkFZVEFrUkYKT\
      VNRd0lnWURWUVFLREJ0RVpYVjBjMk5vWlNCU1pXNTBaVzUyWlhKemFXTm9aWEoxYm1jeEV6QVJCZ\
      05WQkFzTQpDazVSSUZKdmIzUWdRMEV4R2pBWUJnTlZCQU1NRVVSU1ZpQlNiMjkwSUVOQklESXdNV\
      GhoTUI0WERURTRNVEl3Ck5qRTBORE14TUZvWERUSTRNVEl6TVRJeU5UazFPVm93WlRFTE1Ba0dBM\
      VVFQmhNQ1JFVXhKREFpQmdOVkJBb00KRzBSbGRYUnpZMmhsSUZKbGJuUmxiblpsY25OcFkyaGxjb\
      lZ1WnpFVk1CTUdBMVVFQ3d3TVRsRWdSRkpXSUZSTgpJRU5CTVJrd0Z3WURWUVFEREJCRVVsWWdWR\
      TBnUTBFZ01qQXhPR0ZoTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBU\
      UVBcllCMlk1bDMrcHQwSGxjSVJzdmp1ZkswSkl2TFQxTFBuWit4eG4xVzJ6VjMKTUdKa0NnVmZIS\
      EFyMmFwUC96dlBpM1JjaWNjQmZIcCt3Y210TDJxNytnb3hqT1B5Q3dOMWREMTVReVlMbGFXYwpSd\
      FM4bGtXdktDNmhhZlcvZXFKaC9XcGxRejJMeXFxWkdWS1BuejRjcnZSNFBKU245SVNCYnp6cGxZU\
      VJ4bVMwCkp6ckNRUG1SREpHWFJ5SVFGTGMxc1owVVluRHdEUXhWTG9qS1JIUkNyVFRWZDZxUjR5M\
      DY1ejJwZzZiQkRJb3IKVEZsY3FjRGpzb2ViM01BSTk2N2RjRUZQSjBLdngwaFpqSUt0czlzdVQ1O\
      Fh6eWdBd3JoOTZYVk1lLzlBOHdjYQpmR2xkNktKZkhCS1ltazZTY3BsdUhkWjN0Z2Y3UmNrTXI4V\
      WFjR3hLYVFJREFRQUJvNElEaGpDQ0E0SXdFd1lEClZSMGpCQXd3Q29BSVRwbTBUdWR0VUNJd1RnW\
      UlLd1lCQlFVSEFRRUVRakJBTUQ0R0NDc0dBUVVGQnpBQmhqSm8KZEhSd09pOHZiMk56Y0MxeWIyO\
      TBMblJqTG1SbGRYUnpZMmhsTFhKbGJuUmxiblpsY25OcFkyaGxjblZ1Wnk1awpaVEIzQmdOVkhTQ\
      UVjREJ1TUd3R0RTc0dBUVFCZ2EwOEFRZ0NBUUV3V3pCWkJnZ3JCZ0VGQlFjQ0FSWk5hSFIwCmNEb\
      3ZMM2QzZHk1a1pYVjBjMk5vWlMxeVpXNTBaVzUyWlhKemFXTm9aWEoxYm1jdFluVnVaQzVrWlM5e\
      mRHRjAKYVdNdmRISjFjM1JqWlc1MFpYSXZjRzlzYVdONUxtaDBiV3d3Z2dGR0JnTlZIUjhFZ2dFO\
      U1JSUJPVEI5b0h1ZwplWVozYkdSaGNEb3ZMMlJwY2k1MFl5NWtaWFYwYzJOb1pTMXlaVzUwWlc1M\
      lpYSnphV05vWlhKMWJtY3VaR1V2ClkyNDlOekEyTnpVM0xHOTFQVTVSSlRJd1VtOXZkQ1V5TUVOQ\
      kxHTnVQVkIxWW14cFl5eHZQVVJTVml4alBVUkYKUDJObGNuUnBabWxqWVhSbFVtVjJiMk5oZEdsd\
      mJreHBjM1F3Z2JlZ2diU2dnYkdHZ2E1b2RIUndPaTh2WkdseQpMblJqTG1SbGRYUnpZMmhsTFhKb\
      GJuUmxiblpsY25OcFkyaGxjblZ1Wnk1a1pTOXpaWEoyYkdWMEwwUnBjbGgzClpXSXZRMkV2ZUM1a\
      mNtdy9aRzQ5WTI0bE0wUTNNRFkzTlRjbE1rTnZkU1V6UkU1UkpUSXdVbTl2ZENVeU1FTkIKSlRKR\
      FkyNGxNMFJRZFdKc2FXTWxNa052SlRORVJGSldKVEpEWXlVelJFUkZKbUYwZEhKdVlXMWxQV05sY\
      25ScApabWxqWVhSbFVtVjJiMk5oZEdsdmJreHBjM1F3Z2dFZkJnTlZIUklFZ2dFV01JSUJFb1pyY\
      kdSaGNEb3ZMMlJwCmNpNTBZeTVrWlhWMGMyTm9aUzF5Wlc1MFpXNTJaWEp6YVdOb1pYSjFibWN1W\
      kdVdlkyNDlOekEyTnpVM0xHOTEKUFU1UkpUSXdVbTl2ZENVeU1FTkJMR051UFZCMVlteHBZeXh2U\
      FVSU1ZpeGpQVVJGUDJOQlEyVnlkR2xtYVdOaApkR1dHZ2FKb2RIUndPaTh2WkdseUxuUmpMbVJsZ\
      FhSelkyaGxMWEpsYm5SbGJuWmxjbk5wWTJobGNuVnVaeTVrClpTOXpaWEoyYkdWMEwwUnBjbGgzW\
      ldJdlEyRXZlQzVqWlhJL1pHNDlZMjRsTTBRM01EWTNOVGNsTWtOdmRTVXoKUkU1UkpUSXdVbTl2Z\
      ENVeU1FTkJKVEpEWTI0bE0wUlFkV0pzYVdNbE1rTnZKVE5FUkZKV0pUSkRZeVV6UkVSRgpKbUYwZ\
      EhKdVlXMWxQV05CUTJWeWRHbG1hV05oZEdVd0VRWURWUjBPQkFvRUNFazlkbG1YOWZVNE1BNEdBM\
      VVkCkR3RUIvd1FFQXdJQkJqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQTBHQ1NxR1NJYjNEU\
      UVCQ3dVQUE0SUIKQVFCbDdwendLUUlyT0xCc01RanpDSjRKMmEvM1ErSVpZSjVFZWJ6RDNpOU93M\
      mtkMk1ZRkw4TmRmaFZUL2UxaApqcTVaUnNNeWd4VmN6WEw3WUljdnEwSTJ2Q0FCMExvbXorUDUrb\
      0dHdGs2VlNOekhBb2dEcml6RFp0Q3cxTHpVCnVjNVY5YzBScC9UNENhWjhLWlRRcWhKdjJTNjYrN\
      jBydThuQk1nenBwdEQ3K3J6eXBPUnVuUGs2akFTWnlaUlkKVTNUVEQzK2lnNVRSTnZGaVZYd1liN\
      DJZZFlybnVPRGpQN0IxbTJZQk5LVW1ndjJudFVXckVnRUpwaTdvT20wegpOSmQ0SkdoQUd4ajUxW\
      m12bUxScFpORUl3bkFrRUI3aWllcElzK0J6dG1KOVhiVmQ4R29yclU5QU1SaXVMOXd1Cm00eERYU\
      0dQZ0U4amRTOTVETTEyQ0dKMgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ\
      0VSVElGSUNBVEUtLS0tLQpNSUlEOWpDQ0F0NmdBd0lCQWdJRENzakZNQTBHQ1NxR1NJYjNEUUVCQ\
      3dVQU1HUXhDekFKQmdOVkJBWVRBa1JGCk1TUXdJZ1lEVlFRS0RCdEVaWFYwYzJOb1pTQlNaVzUwW\
      lc1MlpYSnphV05vWlhKMWJtY3hFekFSQmdOVkJBc00KQ2s1UklGSnZiM1FnUTBFeEdqQVlCZ05WQ\
      kFNTUVVUlNWaUJTYjI5MElFTkJJREl3TVRoaE1CNFhEVEU0TVRJdwpOVEV5TXpZeE9Gb1hEVEk0T\
      VRJek1USXlOVGsxT1Zvd1pERUxNQWtHQTFVRUJoTUNSRVV4SkRBaUJnTlZCQW9NCkcwUmxkWFJ6W\
      TJobElGSmxiblJsYm5abGNuTnBZMmhsY25WdVp6RVRNQkVHQTFVRUN3d0tUbEVnVW05dmRDQkQKU\
      VRFYU1CZ0dBMVVFQXd3UlJGSldJRkp2YjNRZ1EwRWdNakF4T0dFd2dnRWlNQTBHQ1NxR1NJYjNEU\
      UVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFEQkhuMWFhOE00YitRTGxTNmdrL0pJSy9wZnM0M2J0d\
      WZWbUhOQnJ6bmh1VmRBCnh0b1BaWlBBbXFBZ3grTnFaVHNZZFpWTS81L2doL2l2V01UelJUOVhVW\
      kFvdlRjTVNlQnZtRnFFMm44M2N4VXIKRG9lMi9raHV6TVNRU2FneU1uQ0JFNThoaTdTZHhqY2xIM\
      Ug2MHZnNzBGRGlkcnRNcjVHMkNmYXovNUNDMUF3OApxSlJXMTJzWXhsNHFVZUQ5cjRVRnNGeHdqN\
      VhjMXhUSjF6c2FucDNvdktaLytOZkdJVlVsTHprSEpiVFcxVlZsCnU0d1VQMEkvWFQyZHBVTUgrV\
      HRNOGtLU2xZNlB2RC9JYTZ3cHdWb1J4MThibVdmaDZyLzVDZDFMLyt1RTVENnkKV0hzakk1SVVmM\
      E84S0RWYU1hNForL3poSUFNOVYwdzhFb3RwM3BrUkFnTUJBQUdqZ2JBd2dhMHdEd1lEVlIwVApBU\
      UgvQkFVd0F3RUIvekFSQmdOVkhRNEVDZ1FJVHBtMFR1ZHRVQ0l3ZHdZRFZSMGdCSEF3YmpCc0JnM\
      HJCZ0VFCkFZR3RQQUVJQWdFQk1Gc3dXUVlJS3dZQkJRVUhBZ0VXVFdoMGRIQTZMeTkzZDNjdVpHV\
      jFkSE5qYUdVdGNtVnUKZEdWdWRtVnljMmxqYUdWeWRXNW5MV0oxYm1RdVpHVXZjM1JoZEdsakwzU\
      nlkWE4wWTJWdWRHVnlMM0J2YkdsagplUzVvZEcxc01BNEdBMVVkRHdFQi93UUVBd0lCQmpBTkJna\
      3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUVNQ0orRlMwCjVNdis2MkNWRU5tcWord3U0bE1adWdnbnhpW\
      GI4Zmw3anFJZVEvK3BOK0JzM2d1dUorY3dRdG96TGhwcjltMkYKOVhVV2I1QmtPeWpDVFlZNzFCU\
      W9nMnh6aXV6Z3lBNG1qcHV4QWNqeGpqOXB0KzdMZ2h0cTNJeXJwa3lwaVREYgo2Wm9hNGpXZ05SM\
      nhHZ2xQWHJnUDdCTVlJRlQyYmVVSE9WbkhycFo3VVk5K0VJQ2d0NmlyUnJrSkRHT2pMckRuCmdJW\
      kxSSUFuZlJveG02UjZSdTYrcDh4RjUyQnAzUTR6R294ZTdJVWRUalJQWEJuQ1lBWjduNmpubzNWe\
      lgxOUwKK1MzUVZHaGRGRkdlVjhVNlZ5UkwvbFJIRStmd3Jxdi9BWElhYi9zMVNOenFscG4zSWZ6Y\
      2pjMHozajZGZyszRwpqS2YzUXlQTDhYN3YvZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0="

users:
- name: "customer-kne"
  user:
    token: "kubeconfig-user-6zqsrhvtn6:667vswhxhx4vkp2jq2xwvqct95rqspz4dlxdxkrm9lxdn42pxqmtlb"


contexts:
- name: "customer-kne"
  context:
    user: "customer-kne"
    cluster: "customer-kne"

current-context: "customer-kne"
